version: '3.8'
services:
    web:
      build: .
      command: npm run start:dev
      volumes:
        - .:/usr/app/
      ports:
        - "3000:3000"
      depends_on:
        - db
      networks:
          network:
              ipv4_address: 172.0.0.4
    db:
        container_name: nestjs-auth-db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: auth
        ports:
            - "5432:5432"
        networks:
            network:
                ipv4_address: 172.0.0.2
    pgadmin:
        container_name: nestjs-auth-pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        depends_on:
            - db
        networks:
            network:
                ipv4_address: 172.0.0.3
networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.0.0.0/29